export const LIMITS = {
  PAGINATION: {
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },
  FILE_SIZE: {
    MAX_UPLOAD_MB: 10,
  },
  RATE_LIMIT: {
    PUBLIC_WINDOW_MS: 15 * 60 * 1000,
    PUBLIC_MAX_REQUESTS: 100,
  },
};
