// Automatically generated by scripts/generate-releases.mjs
export interface ReleaseAsset {
  name: string;
  platform: string;
  downloadUrl: string;
  sizeBytes: number;
  checksum: string;
}

export interface Release {
  version: string;
  releaseDate: string;
  prerelease: boolean;
  releaseNotes: string;
  assets: ReleaseAsset[];
}

export const GENERATED_RELEASES: Release[] = [
  {
    "version": "v1.1.1-beta.4.2",
    "releaseDate": "2026-09-02T18:36:18Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.2/latest.yml",
        "sizeBytes": 383,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.4.2-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.2/LeadForge.OS-1.1.1-beta.4.2-win-x64.exe",
        "sizeBytes": 99874466,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.4.2-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.2/LeadForge.OS-1.1.1-beta.4.2-win-x64.exe.blockmap",
        "sizeBytes": 103759,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.4.2-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.2/LeadForge.OS-1.1.1-beta.4.2-win-x64.exe.sha256",
        "sizeBytes": 106,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.1.1-beta.4.1",
    "releaseDate": "2026-09-02T15:13:34Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.1/latest.yml",
        "sizeBytes": 383,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.4.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.1/LeadForge.OS-1.1.1-beta.4.1-win-x64.exe",
        "sizeBytes": 99870937,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.4.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.1/LeadForge.OS-1.1.1-beta.4.1-win-x64.exe.blockmap",
        "sizeBytes": 103376,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.4.1-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.4.1/LeadForge.OS-1.1.1-beta.4.1-win-x64.exe.sha256",
        "sizeBytes": 106,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.1.1-beta.3",
    "releaseDate": "2026-09-02T12:23:56Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.3/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.3-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.3/LeadForge.OS-1.1.1-beta.3-win-x64.exe",
        "sizeBytes": 99871395,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.3-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.3/LeadForge.OS-1.1.1-beta.3-win-x64.exe.blockmap",
        "sizeBytes": 104008,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.3-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.3/LeadForge.OS-1.1.1-beta.3-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.1.1-beta.2",
    "releaseDate": "2026-08-26T21:13:38Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.2/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.2-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.2/LeadForge.OS-1.1.1-beta.2-win-x64.exe",
        "sizeBytes": 99907618,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.2-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.2/LeadForge.OS-1.1.1-beta.2-win-x64.exe.blockmap",
        "sizeBytes": 104321,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.2-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.2/LeadForge.OS-1.1.1-beta.2-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.1.1-beta.1",
    "releaseDate": "2026-08-25T15:31:56Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.1/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.1/LeadForge.OS-1.1.1-beta.1-win-x64.exe",
        "sizeBytes": 99874639,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.1/LeadForge.OS-1.1.1-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 103514,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.1.1-beta.1-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.1.1-beta.1/LeadForge.OS-1.1.1-beta.1-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.0.0-beta.6",
    "releaseDate": "2026-08-25T14:49:24Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.6/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.6-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.6/LeadForge.OS-1.0.0-beta.6-win-x64.exe",
        "sizeBytes": 99874712,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.6-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.6/LeadForge.OS-1.0.0-beta.6-win-x64.exe.blockmap",
        "sizeBytes": 103474,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.6-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.6/LeadForge.OS-1.0.0-beta.6-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.0.0-beta.5",
    "releaseDate": "2026-08-05T19:04:53Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.5/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.5-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.5/LeadForge.OS-1.0.0-beta.5-win-x64.exe",
        "sizeBytes": 99547638,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.5-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.5/LeadForge.OS-1.0.0-beta.5-win-x64.exe.blockmap",
        "sizeBytes": 103425,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.5-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.5/LeadForge.OS-1.0.0-beta.5-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.0.0-beta.4",
    "releaseDate": "2026-08-05T18:16:47Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.4/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.4-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.4/LeadForge.OS-1.0.0-beta.4-win-x64.exe",
        "sizeBytes": 99546828,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.4-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.4/LeadForge.OS-1.0.0-beta.4-win-x64.exe.blockmap",
        "sizeBytes": 103471,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.4-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.4/LeadForge.OS-1.0.0-beta.4-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.0.0-beta.3",
    "releaseDate": "2026-08-05T17:44:10Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.3-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/LeadForge.OS-1.0.0-beta.3-win-x64.exe",
        "sizeBytes": 99546859,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.3-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/LeadForge.OS-1.0.0-beta.3-win-x64.exe.blockmap",
        "sizeBytes": 103578,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.3-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/LeadForge.OS-1.0.0-beta.3-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.0.0-beta.2",
    "releaseDate": "2026-08-05T02:51:42Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": []
  },
  {
    "version": "v1.0.0-beta.1",
    "releaseDate": "2026-08-01T14:33:36Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.1/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.2-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.1/LeadForge.OS-0.1.2-beta.1-win-x64.exe",
        "sizeBytes": 99520493,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.2-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.1/LeadForge.OS-0.1.2-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 103163,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v0.1.2-beta.1",
    "releaseDate": "2026-08-01T14:03:16Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.2-beta.1/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.1-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.2-beta.1/LeadForge.OS-0.1.1-beta.1-win-x64.exe",
        "sizeBytes": 98456697,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.1-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.2-beta.1/LeadForge.OS-0.1.1-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 103832,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v0.1.1-beta.1",
    "releaseDate": "2026-08-01T09:35:57Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.1-beta.1/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.1-beta.1/LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "sizeBytes": 98454876,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.1-beta.1/LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 104017,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v0.1.0-beta.2",
    "releaseDate": "2026-08-01T09:28:57Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.0-beta.2/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.0-beta.2/LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "sizeBytes": 98454858,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.0-beta.2/LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 103974,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  }
];
