// Automatically generated by scripts/generate-contributors.mjs
export interface Contributor {
  login: string;
  id: number;
  avatar_url: string;
  html_url: string;
  contributions: number;
}

export const GENERATED_CONTRIBUTORS: Contributor[] = [
  {
    "login": "kjxcodez",
    "id": 103230903,
    "avatar_url": "https://avatars.githubusercontent.com/u/103230903?v=4",
    "html_url": "https://github.com/kjxcodez",
    "contributions": 460
  },
  {
    "login": "github-actions[bot]",
    "id": 41898282,
    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
    "html_url": "https://github.com/apps/github-actions",
    "contributions": 6
  }
];
