// Automatically generated by scripts/generate-contributors.mjs
export interface Contributor {
  login: string;
  id: number;
  avatar_url: string;
  html_url: string;
  contributions: number;
}

export const GENERATED_CONTRIBUTORS: Contributor[] = [
  {
    "login": "kjxcodez",
    "id": 104273295,
    "avatar_url": "https://github.com/kjxcodez.png",
    "html_url": "https://github.com/kjxcodez",
    "contributions": 218
  }
];
