// Automatically generated by scripts/generate-releases.mjs
export interface ReleaseAsset {
  name: string;
  platform: string;
  downloadUrl: string;
  sizeBytes: number;
  checksum: string;
}

export interface Release {
  version: string;
  releaseDate: string;
  prerelease: boolean;
  releaseNotes: string;
  assets: ReleaseAsset[];
}

export const GENERATED_RELEASES: Release[] = [
  {
    "version": "v1.0.0-beta.3",
    "releaseDate": "2026-08-05T17:44:10Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.3-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/LeadForge.OS-1.0.0-beta.3-win-x64.exe",
        "sizeBytes": 99546859,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.3-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/LeadForge.OS-1.0.0-beta.3-win-x64.exe.blockmap",
        "sizeBytes": 103578,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-1.0.0-beta.3-win-x64.exe.sha256",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.3/LeadForge.OS-1.0.0-beta.3-win-x64.exe.sha256",
        "sizeBytes": 104,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v1.0.0-beta.2",
    "releaseDate": "2026-08-05T02:51:42Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": []
  },
  {
    "version": "v1.0.0-beta.1",
    "releaseDate": "2026-08-01T14:33:36Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.1/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.2-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.1/LeadForge.OS-0.1.2-beta.1-win-x64.exe",
        "sizeBytes": 99520493,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.2-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v1.0.0-beta.1/LeadForge.OS-0.1.2-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 103163,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v0.1.2-beta.1",
    "releaseDate": "2026-08-01T14:03:16Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.2-beta.1/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.1-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.2-beta.1/LeadForge.OS-0.1.1-beta.1-win-x64.exe",
        "sizeBytes": 98456697,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.1-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.2-beta.1/LeadForge.OS-0.1.1-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 103832,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v0.1.1-beta.1",
    "releaseDate": "2026-08-01T09:35:57Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.1-beta.1/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.1-beta.1/LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "sizeBytes": 98454876,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.1-beta.1/LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 104017,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  },
  {
    "version": "v0.1.0-beta.2",
    "releaseDate": "2026-08-01T09:28:57Z",
    "prerelease": true,
    "releaseNotes": "",
    "assets": [
      {
        "name": "latest.yml",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.0-beta.2/latest.yml",
        "sizeBytes": 377,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "platform": "Windows (x64)",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.0-beta.2/LeadForge.OS-0.1.0-beta.1-win-x64.exe",
        "sizeBytes": 98454858,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      },
      {
        "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "platform": "Other",
        "downloadUrl": "https://github.com/kjxcodez/leadforge-os/releases/download/v0.1.0-beta.2/LeadForge.OS-0.1.0-beta.1-win-x64.exe.blockmap",
        "sizeBytes": 103974,
        "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      }
    ]
  }
];
