"use client"

import React, { useState } from "react"
import { Check, Copy } from "lucide-react"

export function Pre({ children, ...props }: React.HTMLAttributes<HTMLPreElement>) {
  const [copied, setCopied] = useState(false)

  // Recursively extract raw text content from React children
  const extractText = (node: any): string => {
    if (!node) return ""
    if (typeof node === "string") return node
    if (typeof node === "number") return String(node)
    if (Array.isArray(node)) return node.map(extractText).join("")
    if (node.props && node.props.children) return extractText(node.props.children)
    return ""
  }

  const handleCopy = () => {
    const rawText = extractText(children)
    navigator.clipboard.writeText(rawText.trim())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  // Safely extract the language attribute generated by rehype-pretty-code
  const language = (children as any)?.props?.["data-language"] || "code"

  return (
    <div className="my-6 border border-[var(--border-subtle)] rounded-lg overflow-hidden bg-[rgba(8,8,9,0.75)] backdrop-blur-sm shadow-[0_4px_20px_rgba(0,0,0,0.25)] relative group/pre">
      {/* Code Header Bar */}
      <div className="flex h-9 items-center justify-between border-b border-[var(--border-subtle)] bg-[var(--card)] px-4 select-none">
        <div className="flex gap-1.5">
          <span className="h-2 w-2 rounded-full bg-red-500/50 hover:bg-red-500 transition-colors"></span>
          <span className="h-2 w-2 rounded-full bg-yellow-500/50 hover:bg-yellow-500 transition-colors"></span>
          <span className="h-2 w-2 rounded-full bg-green-500/50 hover:bg-green-500 transition-colors"></span>
        </div>
        
        {/* Language Badge */}
        <span className="text-[9px] text-[var(--text-tertiary)] uppercase tracking-wider font-semibold font-sans">
          {language}
        </span>

        {/* Copy Button */}
        <button 
          onClick={handleCopy}
          className="text-[9px] font-medium text-[var(--text-tertiary)] hover:text-[var(--foreground)] flex items-center gap-1 cursor-pointer bg-transparent border-0 outline-none transition-colors"
        >
          {copied ? (
            <span className="flex items-center gap-1 text-[var(--success)] font-semibold">
              <Check className="h-3 w-3" /> Copied
            </span>
          ) : (
            <span className="flex items-center gap-1">
              <Copy className="h-3 w-3 opacity-60 group-hover/pre:opacity-100 transition-opacity" /> Copy
            </span>
          )}
        </button>
      </div>

      {/* Code Area */}
      <pre 
        {...props} 
        className="p-4 overflow-x-auto text-[var(--muted-foreground)] leading-relaxed text-[11px] custom-scrollbar bg-transparent select-text"
      >
        {children}
      </pre>
    </div>
  )
}
