import {
  API_VERSION as SHARED_API_VERSION,
  API_PREFIX as SHARED_API_PREFIX,
  LIMITS as SHARED_LIMITS,
  TIMEOUTS as SHARED_TIMEOUTS,
  COLLECTION_NAMES as SHARED_COLLECTION_NAMES,
} from '@leadforge/core';

export const API_VERSION = SHARED_API_VERSION;
export const API_PREFIX = SHARED_API_PREFIX;

export const LIMITS = {
  DEFAULT_PAGE_SIZE: SHARED_LIMITS.PAGINATION.DEFAULT_LIMIT,
  MAX_PAGE_SIZE: SHARED_LIMITS.PAGINATION.MAX_LIMIT,
  DB_POOL_MIN: 2,
  DB_POOL_MAX: 10,
};

export const TIMEOUTS = {
  DB_CONNECT_RETRY: SHARED_TIMEOUTS.DB_CONNECTION / 5, // 2000
  DB_SELECTION_MS: 5000,
  SOCKET_MS: 45000,
};

export const COLLECTION_NAMES = SHARED_COLLECTION_NAMES;
